#!/bin/sh

result=`./suggest-commit <<EOF
diff a/slime.c b/slime.c
index adfads
--- a/slime.c
+++ b/slime.c
-  void hello()  {
-  }
-      hello();
+  void goodbye()  {
+  }
+      goodbye();
EOF
`

[ "$result" = 'Rename `hello` to `goodbye`' ] || exit 1
